### ISSUE TITLE
Which unistd.h are you using on Windows?

### ISSUE THREAD

**Issue by aidinabedi** [planetbeing/libdmg-hfsplus#11]
Hello!

I'm having difficulties compiling the master branch on Windows/VS2013. I'm wondering if you are using any dependencies like Cygwin or MinGW? Or if you have simply found a suitable light-weight replacement (I tried http://stackoverflow.com/a/826027 but it didn't work)?

Cheers,

**Comment by Hesham-Salama** [comment]
Exact same issue.. I tried MinGW and didn't work either. Also tried the same link. Seems to work only in Linux,
